<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gem</groupId>
        <artifactId>baize-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>baize</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>baize</name>
    <description>白泽项目</description>

    <properties>
        <baize.version>0.0.1-SNAPSHOT</baize.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.gem</groupId>
                <artifactId>baize-common-core</artifactId>
                <version>${baize.version}</version>
            </dependency>

            <dependency>
                <groupId>com.gem</groupId>
                <artifactId>baize-common-security</artifactId>
                <version>${baize.version}</version>
            </dependency>

            <dependency>
                <groupId>com.gem</groupId>
                <artifactId>baize-api-admin</artifactId>
                <version>${baize.version}</version>
            </dependency>

            <dependency>
                <groupId>com.gem</groupId>
                <artifactId>baize-common-database</artifactId>
                <version>${baize.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>baize-api</module>
        <module>baize-gateway</module>
        <module>baize-auth</module>
        <module>baize-common</module>
        <module>baize-modules</module>
    </modules>
</project>