enabled: true
image:
  repository: postgres
  tag: latest
auth:
  username: postgres
  password: "baize@2023"
service:
  port: 5432
  nodePort: 30432
persistence:
  enabled: false
  storageClass: ""
  size: 8Gi