insert into sys_user(id, dept_id, user_name, nick_name, user_type, email, phone, gender, avatar,password, sort, login_ip, login_date, status, deleted, revision, created_by,created_time, modified_by, modified_time, remark) values ('1', '1', 'admin', '超级管理员', '00', '1019866833@qq.com', '18715003021', '0', '', '$2a$10$Fk/AFdAuCBNpUYG4uNLAoOE5GbIIA8joG4CPJMJ7LWaxgMDgHHJoe', '0', '127.0.0.1', now(),'0', '0', '0', 'admin', now(), 'admin', now(), '系统管理员');

insert into sys_dept(id, parent_id, ancestors, dept_name, leader, phone, email, sort, status, deleted,revision, created_by, created_time, modified_by, modified_time, remark) values ('1', '0', '0', '研发部', '', '18715003021', '1019866833@qq.com', 1, '0', '0', 0, 'admin', now(), 'admin', now(), '系统管理员');

insert into sys_role(id, role_name, role_key, data_scope, sort, status, deleted, revision, created_by,created_time, modified_by, modified_time, remark) values ('1', '管理员', 'admin', '1', 1, '0', '0', '0', 'admin', now(), 'admin', now(), '系统管理员');
insert into sys_role(id, role_name, role_key, data_scope, sort, status, deleted, revision, created_by,created_time, modified_by, modified_time, remark) values ('2', '普通角色', 'common', '1', 1, '0', '0', '0', 'admin', now(), 'admin', now(), '普通角色');


insert into sys_post (id, post_code, post_name, sort, status, deleted, revision, created_by, created_time, modified_by, modified_time, remark) values ('1', 'ceo',  '董事长',    1, '0', '0',0,'admin', now(), 'admin', now(), '');
insert into sys_post (id, post_code, post_name, sort, status, deleted, revision, created_by, created_time, modified_by, modified_time, remark) values ('2', 'se',   '项目经理',  2, '0','0',0, 'admin', now(), 'admin', now(), '');
insert into sys_post (id, post_code, post_name, sort, status, deleted, revision, created_by, created_time, modified_by, modified_time, remark) values ('3', 'hr',   '人力资源',  3, '0', '0',0,'admin', now(), 'admin', now(), '');
insert into sys_post (id, post_code, post_name, sort, status, deleted, revision, created_by, created_time, modified_by, modified_time, remark) values ('4', 'user', '普通员工',  4, '0','0',0, 'admin', now(), 'admin', now(), '');


-- 一级菜单
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1', '系统管理', '0', '1', 'system',           null, '', 1, 0, 'M', '0', '0', '', 'system',   'admin', now(), '', null, '系统管理目录');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('2', '系统监控', '0', '2', 'monitor',          null, '', 1, 0, 'M', '0', '0', '', 'monitor',  'admin', now(), '', null, '系统监控目录');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('3', '系统工具', '0', '3', 'tool',             null, '', 1, 0, 'M', '0', '0', '', 'tool',     'admin', now(), '', null, '系统工具目录');
-- 二级菜单
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('100',  '用户管理',       '1',   '1', 'user',       'system/user/index',                 '', 1, 0, 'C', '0', '0', 'system:user:list',        'user',          'admin', now(), '', null, '用户管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('101',  '角色管理',       '1',   '2', 'role',       'system/role/index',                 '', 1, 0, 'C', '0', '0', 'system:role:list',        'peoples',       'admin', now(), '', null, '角色管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('102',  '菜单管理',       '1',   '3', 'menu',       'system/menu/index',                 '', 1, 0, 'C', '0', '0', 'system:menu:list',        'tree-table',    'admin', now(), '', null, '菜单管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('103',  '部门管理',       '1',   '4', 'dept',       'system/dept/index',                 '', 1, 0, 'C', '0', '0', 'system:dept:list',        'tree',          'admin', now(), '', null, '部门管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('104',  '岗位管理',       '1',   '5', 'post',       'system/post/index',                 '', 1, 0, 'C', '0', '0', 'system:post:list',        'post',          'admin', now(), '', null, '岗位管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('105',  '字典管理',       '1',   '6', 'dict',       'system/dict/index',                 '', 1, 0, 'C', '0', '0', 'system:dict:list',        'dict',          'admin', now(), '', null, '字典管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('106',  '参数设置',       '1',   '7', 'config',     'system/config/index',               '', 1, 0, 'C', '0', '0', 'system:config:list',      'edit',          'admin', now(), '', null, '参数设置菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('107',  '通知公告',       '1',   '8', 'notice',     'system/notice/index',               '', 1, 0, 'C', '0', '0', 'system:notice:list',      'message',       'admin', now(), '', null, '通知公告菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('108',  '日志管理',       '1',   '9', 'log',        '',                                  '', 1, 0, 'M', '0', '0', '',                        'log',           'admin', now(), '', null, '日志管理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('109',  '在线用户',       '2',   '1', 'online',     'monitor/online/index',              '', 1, 0, 'C', '0', '0', 'monitor:online:list',     'online',        'admin', now(), '', null, '在线用户菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('110',  '定时任务',       '2',   '2', 'job',        'monitor/job/index',                 '', 1, 0, 'C', '0', '0', 'monitor:job:list',        'job',           'admin', now(), '', null, '定时任务菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('111',  'Sentinel控制台', '2',   '3', 'http://localhost:8718',        '',                '', 0, 0, 'C', '0', '0', 'monitor:sentinel:list',   'sentinel',      'admin', now(), '', null, '流量控制菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('112',  'Nacos控制台',    '2',   '4', 'http://localhost:8848/nacos',  '',                '', 0, 0, 'C', '0', '0', 'monitor:nacos:list',      'nacos',         'admin', now(), '', null, '服务治理菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('113',  'Admin控制台',    '2',   '5', 'http://localhost:9100/login',  '',                '', 0, 0, 'C', '0', '0', 'monitor:server:list',     'server',        'admin', now(), '', null, '服务监控菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('114',  '表单构建',       '3',   '1', 'build',      'tool/build/index',                  '', 1, 0, 'C', '0', '0', 'tool:build:list',         'build',         'admin', now(), '', null, '表单构建菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('115',  '代码生成',       '3',   '2', 'gen',        'tool/gen/index',                    '', 1, 0, 'C', '0', '0', 'tool:gen:list',           'code',          'admin', now(), '', null, '代码生成菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('116',  '系统接口',       '3',   '3', 'http://localhost:8080/swagger-ui/index.html', '', '', 0, 0, 'C', '0', '0', 'tool:swagger:list',       'swagger',       'admin', now(), '', null, '系统接口菜单');
-- 三级菜单
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('500',  '操作日志', '108', '1', 'operlog',    'system/operlog/index',    '', 1, 0, 'C', '0', '0', 'system:operlog:list',    'form',          'admin', now(), '', null, '操作日志菜单');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('501',  '登录日志', '108', '2', 'logininfor', 'system/logininfor/index', '', 1, 0, 'C', '0', '0', 'system:logininfor:list', 'logininfor',    'admin', now(), '', null, '登录日志菜单');

-- 用户管理按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1000', '用户查询', '100', '1',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1001', '用户新增', '100', '2',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1002', '用户修改', '100', '3',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1003', '用户删除', '100', '4',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:remove',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1004', '用户导出', '100', '5',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:export',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1005', '用户导入', '100', '6',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:import',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1006', '重置密码', '100', '7',  '', '', '', 1, 0, 'F', '0', '0', 'system:user:resetPwd',       '#', 'admin', now(), '', null, '');
-- 角色管理按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1007', '角色查询', '101', '1',  '', '', '', 1, 0, 'F', '0', '0', 'system:role:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1008', '角色新增', '101', '2',  '', '', '', 1, 0, 'F', '0', '0', 'system:role:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1009', '角色修改', '101', '3',  '', '', '', 1, 0, 'F', '0', '0', 'system:role:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1010', '角色删除', '101', '4',  '', '', '', 1, 0, 'F', '0', '0', 'system:role:remove',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1011', '角色导出', '101', '5',  '', '', '', 1, 0, 'F', '0', '0', 'system:role:export',         '#', 'admin', now(), '', null, '');
-- 菜单管理按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1012', '菜单查询', '102', '1',  '', '', '', 1, 0, 'F', '0', '0', 'system:menu:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1013', '菜单新增', '102', '2',  '', '', '', 1, 0, 'F', '0', '0', 'system:menu:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1014', '菜单修改', '102', '3',  '', '', '', 1, 0, 'F', '0', '0', 'system:menu:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1015', '菜单删除', '102', '4',  '', '', '', 1, 0, 'F', '0', '0', 'system:menu:remove',         '#', 'admin', now(), '', null, '');
-- 部门管理按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1016', '部门查询', '103', '1',  '', '', '', 1, 0, 'F', '0', '0', 'system:dept:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1017', '部门新增', '103', '2',  '', '', '', 1, 0, 'F', '0', '0', 'system:dept:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1018', '部门修改', '103', '3',  '', '', '', 1, 0, 'F', '0', '0', 'system:dept:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1019', '部门删除', '103', '4',  '', '', '', 1, 0, 'F', '0', '0', 'system:dept:remove',         '#', 'admin', now(), '', null, '');
-- 岗位管理按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1020', '岗位查询', '104', '1',  '', '', '', 1, 0, 'F', '0', '0', 'system:post:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1021', '岗位新增', '104', '2',  '', '', '', 1, 0, 'F', '0', '0', 'system:post:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1022', '岗位修改', '104', '3',  '', '', '', 1, 0, 'F', '0', '0', 'system:post:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1023', '岗位删除', '104', '4',  '', '', '', 1, 0, 'F', '0', '0', 'system:post:remove',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1024', '岗位导出', '104', '5',  '', '', '', 1, 0, 'F', '0', '0', 'system:post:export',         '#', 'admin', now(), '', null, '');
-- 字典管理按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1025', '字典查询', '105', '1', '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1026', '字典新增', '105', '2', '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1027', '字典修改', '105', '3', '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1028', '字典删除', '105', '4', '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:remove',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1029', '字典导出', '105', '5', '#', '', '', 1, 0, 'F', '0', '0', 'system:dict:export',         '#', 'admin', now(), '', null, '');
-- 参数设置按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1030', '参数查询', '106', '1', '#', '', '', 1, 0, 'F', '0', '0', 'system:config:query',        '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1031', '参数新增', '106', '2', '#', '', '', 1, 0, 'F', '0', '0', 'system:config:add',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1032', '参数修改', '106', '3', '#', '', '', 1, 0, 'F', '0', '0', 'system:config:edit',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1033', '参数删除', '106', '4', '#', '', '', 1, 0, 'F', '0', '0', 'system:config:remove',       '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1034', '参数导出', '106', '5', '#', '', '', 1, 0, 'F', '0', '0', 'system:config:export',       '#', 'admin', now(), '', null, '');
-- 通知公告按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1035', '公告查询', '107', '1', '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:query',        '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1036', '公告新增', '107', '2', '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:add',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1037', '公告修改', '107', '3', '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:edit',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1038', '公告删除', '107', '4', '#', '', '', 1, 0, 'F', '0', '0', 'system:notice:remove',       '#', 'admin', now(), '', null, '');
-- 操作日志按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1039', '操作查询', '500', '1', '#', '', '', 1, 0, 'F', '0', '0', 'system:operlog:query',       '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1040', '操作删除', '500', '2', '#', '', '', 1, 0, 'F', '0', '0', 'system:operlog:remove',      '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1041', '日志导出', '500', '3', '#', '', '', 1, 0, 'F', '0', '0', 'system:operlog:export',      '#', 'admin', now(), '', null, '');
-- 登录日志按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1042', '登录查询', '501', '1', '#', '', '', 1, 0, 'F', '0', '0', 'system:logininfor:query',    '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1043', '登录删除', '501', '2', '#', '', '', 1, 0, 'F', '0', '0', 'system:logininfor:remove',   '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1044', '日志导出', '501', '3', '#', '', '', 1, 0, 'F', '0', '0', 'system:logininfor:export',   '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1045', '账户解锁', '501', '4', '#', '', '', 1, 0, 'F', '0', '0', 'system:logininfor:unlock',   '#', 'admin', now(), '', null, '');
-- 在线用户按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1046', '在线查询', '109', '1', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:online:query',       '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1047', '批量强退', '109', '2', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:online:batchLogout', '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1048', '单条强退', '109', '3', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:online:forceLogout', '#', 'admin', now(), '', null, '');
-- 定时任务按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1049', '任务查询', '110', '1', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:query',          '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1050', '任务新增', '110', '2', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:add',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1051', '任务修改', '110', '3', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:edit',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1052', '任务删除', '110', '4', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:remove',         '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1053', '状态修改', '110', '5', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:changeStatus',   '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1054', '任务导出', '110', '6', '#', '', '', 1, 0, 'F', '0', '0', 'monitor:job:export',         '#', 'admin', now(), '', null, '');
-- 代码生成按钮
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1055', '生成查询', '115', '1', '#', '', '', 1, 0, 'F', '0', '0', 'tool:gen:query',             '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1056', '生成修改', '115', '2', '#', '', '', 1, 0, 'F', '0', '0', 'tool:gen:edit',              '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1057', '生成删除', '115', '3', '#', '', '', 1, 0, 'F', '0', '0', 'tool:gen:remove',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1058', '导入代码', '115', '2', '#', '', '', 1, 0, 'F', '0', '0', 'tool:gen:import',            '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1059', '预览代码', '115', '4', '#', '', '', 1, 0, 'F', '0', '0', 'tool:gen:preview',           '#', 'admin', now(), '', null, '');
insert into sys_menu(id, menu_name, parent_id,sort, path, component, parameters, external,cacheable, menu_type, visible, status,perms,icon, created_by, created_time, modified_by, modified_time, remark) values('1060', '生成代码', '115', '5', '#', '', '', 1, 0, 'F', '0', '0', 'tool:gen:code',              '#', 'admin', now(), '', null, '');


insert into sys_user_role values ('1', '1');
insert into sys_user_role values ('2', '2');

insert into sys_role_menu values ('2', '1');
insert into sys_role_menu values ('2', '2');
insert into sys_role_menu values ('2', '3');
insert into sys_role_menu values ('2', '4');

insert into sys_user_post values ('1','1');



insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark) values(1,  '用户性别', 'sys_user_sex',        '0', 'admin', now(), '', null, '用户性别列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(2,  '菜单状态', 'sys_show_hide',       '0', 'admin', now(), '', null, '菜单状态列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(3,  '系统开关', 'sys_normal_disable',  '0', 'admin', now(), '', null, '系统开关列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(4,  '任务状态', 'sys_job_status',      '0', 'admin', now(), '', null, '任务状态列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(5,  '任务分组', 'sys_job_group',       '0', 'admin', now(), '', null, '任务分组列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(6,  '系统是否', 'sys_yes_no',          '0', 'admin', now(), '', null, '系统是否列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(7,  '通知类型', 'sys_notice_type',     '0', 'admin', now(), '', null, '通知类型列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(8,  '通知状态', 'sys_notice_status',   '0', 'admin', now(), '', null, '通知状态列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(9,  '操作类型', 'sys_oper_type',       '0', 'admin', now(), '', null, '操作类型列表');
insert into sys_dict_type(id,dict_name,dict_type,status,created_by,created_time,modified_by,modified_time,remark)  values(10, '系统状态', 'sys_common_status',   '0', 'admin', now(), '', null, '登录状态列表');




insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(1,  1,  '男',       '0',       'sys_user_sex',        '',   '',        'Y', '0', 'admin', now(), '', null, '性别男');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(2,  2,  '女',       '1',       'sys_user_sex',        '',   '',        'N', '0', 'admin', now(), '', null, '性别女');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(3,  3,  '未知',     '2',       'sys_user_sex',        '',   '',        'N', '0', 'admin', now(), '', null, '性别未知');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(4,  1,  '显示',     '0',       'sys_show_hide',       '',   'primary', 'Y', '0', 'admin', now(), '', null, '显示菜单');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(5,  2,  '隐藏',     '1',       'sys_show_hide',       '',   'danger',  'N', '0', 'admin', now(), '', null, '隐藏菜单');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(6,  1,  '正常',     '0',       'sys_normal_disable',  '',   'primary', 'Y', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(7,  2,  '停用',     '1',       'sys_normal_disable',  '',   'danger',  'N', '0', 'admin', now(), '', null, '停用状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(8,  1,  '正常',     '0',       'sys_job_status',      '',   'primary', 'Y', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(9,  2,  '暂停',     '1',       'sys_job_status',      '',   'danger',  'N', '0', 'admin', now(), '', null, '停用状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(10, 1,  '默认',     'DEFAULT', 'sys_job_group',       '',   '',        'Y', '0', 'admin', now(), '', null, '默认分组');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(11, 2,  '系统',     'SYSTEM',  'sys_job_group',       '',   '',        'N', '0', 'admin', now(), '', null, '系统分组');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(12, 1,  '是',       'Y',       'sys_yes_no',          '',   'primary', 'Y', '0', 'admin', now(), '', null, '系统默认是');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(13, 2,  '否',       'N',       'sys_yes_no',          '',   'danger',  'N', '0', 'admin', now(), '', null, '系统默认否');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(14, 1,  '通知',     '1',       'sys_notice_type',     '',   'warning', 'Y', '0', 'admin', now(), '', null, '通知');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(15, 2,  '公告',     '2',       'sys_notice_type',     '',   'success', 'N', '0', 'admin', now(), '', null, '公告');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(16, 1,  '正常',     '0',       'sys_notice_status',   '',   'primary', 'Y', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(17, 2,  '关闭',     '1',       'sys_notice_status',   '',   'danger',  'N', '0', 'admin', now(), '', null, '关闭状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(18, 99, '其他',     '0',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', now(), '', null, '其他操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(19, 1,  '新增',     '1',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', now(), '', null, '新增操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(20, 2,  '修改',     '2',       'sys_oper_type',       '',   'info',    'N', '0', 'admin', now(), '', null, '修改操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(21, 3,  '删除',     '3',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', now(), '', null, '删除操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(22, 4,  '授权',     '4',       'sys_oper_type',       '',   'primary', 'N', '0', 'admin', now(), '', null, '授权操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(23, 5,  '导出',     '5',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', now(), '', null, '导出操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(24, 6,  '导入',     '6',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', now(), '', null, '导入操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(25, 7,  '强退',     '7',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', now(), '', null, '强退操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(26, 8,  '生成代码', '8',       'sys_oper_type',       '',   'warning', 'N', '0', 'admin', now(), '', null, '生成操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(27, 9,  '清空数据', '9',       'sys_oper_type',       '',   'danger',  'N', '0', 'admin', now(), '', null, '清空操作');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(28, 1,  '成功',     '0',       'sys_common_status',   '',   'primary', 'N', '0', 'admin', now(), '', null, '正常状态');
insert into sys_dict_data (id, sort,dict_label,dict_value,dict_type,css_class, list_class,defaulted,status,created_by, created_time,modified_by, modified_time, remark) values(29, 2,  '失败',     '1',       'sys_common_status',   '',   'danger',  'N', '0', 'admin', now(), '', null, '停用状态');


insert into sys_config(id, config_name, config_key,config_value, config_type, created_by, created_time,modified_by, modified_time, remark) values(1, '主框架页-默认皮肤样式名称',     'sys.index.skinName',       'skin-blue',     'Y', 'admin', now(), '', null, '蓝色 skin-blue、绿色 skin-green、紫色 skin-purple、红色 skin-red、黄色 skin-yellow' );
insert into sys_config(id, config_name, config_key,config_value, config_type, created_by, created_time,modified_by, modified_time, remark) values(2, '用户管理-账号初始密码',         'sys.user.initPassword',    '123456',        'Y', 'admin', now(), '', null, '初始化密码 123456' );
insert into sys_config(id, config_name, config_key,config_value, config_type, created_by, created_time,modified_by, modified_time, remark) values(3, '主框架页-侧边栏主题',           'sys.index.sideTheme',      'theme-dark',    'Y', 'admin', now(), '', null, '深色主题theme-dark，浅色主题theme-light' );
insert into sys_config(id, config_name, config_key,config_value, config_type, created_by, created_time,modified_by, modified_time, remark) values(4, '账号自助-是否开启用户注册功能', 'sys.account.registerUser', 'false',         'Y', 'admin', now(), '', null, '是否开启注册用户功能（true开启，false关闭）');
insert into sys_config(id, config_name, config_key,config_value, config_type, created_by, created_time,modified_by, modified_time, remark) values(5, '用户登录-黑名单列表',           'sys.login.blackIPList',    '',              'Y', 'admin', now(), '', null, '设置登录IP黑名单限制，多个匹配项以;分隔，支持匹配（*通配、网段）');

