<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gem</groupId>
        <artifactId>baize</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>baize-modules</artifactId>
    <packaging>pom</packaging>
    <name>baize-modules</name>
    <description>白泽模块</description>


    <modules>
        <module>baize-admin</module>
    </modules>

</project>
